name: base
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - pip      
  - pip:
    - celery==4.3.0      
    - git+https://github.com/vinay-ebi/production_app.git
    - werkzeug==0.16.1
    - flower  
